language: node_js
node_js:
  - "11.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - ng build --prod
deploy:
  provider: firebase
  token:
    secure: "1//0gDgNDmkDhmiSCgYIARAAGBASNwF-L9IrJeOSx46Z4gw1AXXBjltqVHgS5tsiBTL9zm_xBiMDrVMO6PGaL__5jwz0GqhNQBxd0_Y"
